on: [push]

jobs:
  consolidar_arquivos:
    runs-on: ubuntu-latest
    name: Consolidar arquivos JSON
    steps:
      - name: Consolidar arquivos JSON
        id: mergeJSONs
        uses: biosensu/mergeJSONsAction@v1.1
        with:
          caminho: '/'
          prefixo: 'BS'
