on: [push]

jobs:
  consolidar_arquivos:
    runs-on: ubuntu-latest
    name: Consolidar arquivos JSON
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Consolidar arquivos JSON
        id: mergeJSONs
        uses: biosensu/mergeJSONsAction@v1.14
        with:
          caminho: ${{ github.head_ref }}
          prefixo: 'BS'
      - name: Write File
        id: writeFile
        uses: DamianReeves/write-file-action@v1.3
        with:
          path: ${{ github.workspace }}/consolidado.json
          contents: ${{ steps.mergeJSONs.outputs.consolidado }}
          write-mode: overwrite
      - name: Write File
        id: writeFile2
        uses: DamianReeves/write-file-action@v1.3
        with:
          path: ${{ github.workspace }}/resumo.json
          contents: ${{ steps.mergeJSONs.outputs.resumo }}
          write-mode: overwrite
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated Change
          branch: main
  
            
